version: 2

project_name: claw-mesh

before:
  hooks:
    - go mod tidy

builds:
  - id: claw-mesh
    main: ./cmd/claw-mesh
    binary: claw-mesh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: SallyKAN
      name: homebrew-tap
    name: claw-mesh
    homepage: "https://github.com/SallyKAN/claw-mesh"
    description: "Multi-Gateway orchestrator for OpenClaw"
    license: "MIT"
    install: |
      bin.install "claw-mesh"

release:
  github:
    owner: SallyKAN
    name: claw-mesh
  draft: false
  prerelease: auto
